services:
  spring:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    container_name: quick-reserve-spring
    image: quick-reserve-spring:latest

    restart: always
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/QuickReserve
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root.2024
      SPRING_REDIS_HOST: redis
      SPRING_REDIS_PORT: 6379
      SPRING_REDIS_PASSWORD: root.2024
    depends_on:
      - db
      - redis
  db:
    image: mysql:8.0
    container_name: quick-reserve-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root.2024
      MYSQL_DATABASE: QuickReserve
    ports:
      - "3307:3306"
    volumes:
      - quick-reserve-mysql-data:/var/lib/mysql
  redis:
    image: redis:7.0
    container_name: quick-reserve-redis
    restart: always
    ports:
      - "6380:6379"
    command: ["redis-server", "--requirepass", "root.2024"]
volumes:
  quick-reserve-mysql-data:
