server:
    port: 8081

spring:
    application:
        name: order-service
    profiles:
        active: secret, eureka

    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
        initialization-fail-timeout: 0
        connection-timeout: 30000
        maximum-pool-size: 5

jpa:
    hibernate:
        ddl-auto: update
        jdbc:
            time_zone: Asia/Seoul
        naming:
            strategy: org.hibernate.cfg.ImprovedNamingStrategy
    show-sql: true
    properties:
        hibernate:
            dialect: org.hibernate.dialect.MySQL8Dialect
